### ISSUE TITLE
Unable to add fromJson methods via mixin

### ISSUE THREAD

**Issue by skewty** [Fantom-Factory/afJson#1]
Context: I am very new to Fantom but not to software development.

I am looking to leverage `afJson::Json#` to give my payloads (classes with @JsonProperty) some new skills.
Namely fromJson using your afJson::Json.

My issue is the type specification of the factory method / constructor.

```
const class StartTransaction {
	 
	@JsonProperty 
	const Int type
	
	@JsonProperty 
	const Str id
	
	@JsonProperty 
	const Str command

	static new fromJson(Str jsonStr) {
		return Json().fromJson(jsonStr, StartTransaction#) as StartTransaction
	}
}
```

How do I get the Type# from inside a static method?  I am looking for `This` but it seems invalid.  I want to move `fromJson` into a super class or mixin.  I am guessing this is something you already thought about tried.  Is the lack of Generics going to kill this idea?

**Comment by SlimerDude** [comment]
Hi Scott, I'm not too sure what the question is... to make the above code work, it just needs an it-block ctor so the `const` class may be constructed (by afJson):

```
const class StartTransaction {
	@JsonProperty const Int type
	@JsonProperty const Str id
	@JsonProperty const Str command

	new make(|This| f) { f(this) }
	
	static new fromJson(Str jsonStr) {
		Json().fromJson(jsonStr, StartTransaction#)
	}
}
```

For the more generic question about reflection and the Type system in Fantom, from an instance you would use [Obj.typeof](https://fantom.org/doc/sys/Obj#typeof) - but obviously that doesn't work from a static context.

So yes, from a static context, every Type would need their own static `fromJson()` method because there is no other means to infer a Type.

**Comment by skewty** [comment]
My bad.  My class had the `new make(|This| f) { f(this) }` but as I tried to create a more simple class to include in the issue I forgot to include it.

If every class will need a manually written `fromJson` then it is more code debt than value to me.  Thanks for clearing that up.
